name: Bluesky Card Poster

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    environment: Excavate

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests atproto Pillow

    - name: Post card
      env:
        EXCAVATE_CARDS_BSKY_ACCOUNT: ${{ secrets.EXCAVATE_CARDS_BSKY_ACCOUNT }}
        EXCAVATE_CARDS_BSKY_APP_PASSWORD: ${{ secrets.EXCAVATE_CARDS_BSKY_APP_PASSWORD }}
      run: python bskybot.py
